name: Realease

on:
  push:
    branches:
      - main
    # tags:
    #   - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lame
        run: sudo apt-get install libmp3lame-dev

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
